# Generated by Django 4.2.4 on 2023-08-18 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='catagories/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_price', models.CharField(default='0', max_length=10)),
                ('product_image_url', models.ImageField(null=True, upload_to='products/')),
                ('quantity', models.CharField(default='0', max_length=5, null=True)),
                ('product_description', models.CharField(max_length=1000, null=True)),
                ('data_sheet', models.CharField(max_length=1000, null=True)),
                ('more_info', models.CharField(max_length=1000, null=True)),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userside.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='1', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user')),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user')),
            ],
        ),
    ]
